# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'env | sort'
    - task: Docker@2
      displayName: build and push image
      inputs:
        containerRegistry: 'docker-hub-mittaus'
        repository: 'mittaus/blog-demo'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/docker/web/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          latest